#!/usr/bin/env bash

log_file=../../var/log/error.log
cd tests/e2e

failure="false"

if [ -f $log_file ]
then
    :> $log_file
fi

mkdir -p $(dirname $log_file)
touch $log_file

for e2e_dir in  */
do
    cd "$e2e_dir"
    echo -e "\n$e2e_dir\n";

    make vendor/autoload.php > /dev/null 2>&1
    output="$(make test)"

    if [ $? != 0 ]
    then
        failure="true"
        echo "$e2e_dir" >> ../$log_file
        echo "$output" >> ../$log_file
        echo "" >> ../$log_file
    fi

    cd ..
done

if [ $failure = "true" ]
then
    echo "One of the e2e tests failed, check the logs";
    cat $log_file
    exit 1
fi

echo -e "\nSuccess"
exit 0
