# yamllint disable rule:line-length
# yamllint disable rule:braces

name: Coding Standards

on:
  pull_request:
  push:
    branches:
      - main
      - master

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  coding-standards:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['8.3']
        check:
          - makefile-target: 'php-cs-fixer-lint'
            name: 'PHP-CS-Fixer'
            cache: var/php-cs-fixer-cache
          - makefile-target: 'phpstan'
            name: 'PHPStan'
            cache: var/phpstan-cache
          - makefile-target: 'rector-lint'
            name: 'Rector'
            cache: var/rector-cache

    name: ${{ matrix.check.name }} on PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: Configure ${{ matrix.check.cache }} GitHub Actions cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ matrix.check.cache }}
          key: "${{ matrix.php-version }}-${{ matrix.check.makefile-target }}-${{ github.run_id }}"
          restore-keys: "${{ matrix.php-version }}-${{ matrix.check.makefile-target }}"

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run ${{ matrix.check.makefile-target }}
        run: make ${{ matrix.check.makefile-target }}

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  tests-status:
    name: CS Status
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: coding-standards
    if: always()
    steps:
      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0

      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
